#ifndef CONSTANTS_H
#define CONSTANTS_H

//Constantes pour le labyrinthe 2D

#define LONGUEURFACILE 20/*41*/
#define LARGEURFACILE 15/*31*/
#define LONGUEURMOYEN 30/*61*/
#define LARGEURMOYEN 25/*51*/
#define LONGUEURDIFFICILE 40 /*81*/
#define LARGEURDIFFICILE 35 /*71*/
#define COULEURFOND QColor(255, 255, 255)
#define MOTIFFOND QString(":/Images/resources/background_pattern.png")
#define IMAGEFOND QString(":/Images/resources/background_image.png")
#define COULEURMUR QColor(0, 0, 0)
#define MOTIFMUR QString(":/Images/resources/wall_pattern.png")
#define IMAGEMUR QString(":/Images/resources/wall_image.png")
#define COULEURPARCOURS QColor(64, 64, 64)
#define MOTIFPARCOURS QString(":/Images/resources/way_pattern.png")
#define IMAGEPARCOURS QString(":/Images/resources/way_image.png")
#define TAILLECASE QSize(10, 10)
#define WAYSSIZE QSize(10, 10)
#define WALLSSIZE QSize(10, 10)
#define INTERVALLEROTATIONMAX 1*60*1000
#define INTERVALLEROTATIONMIN 10
#define INTERVALLEROTATION 50
#define ANGLEROTATION 1
#define ROTATIONFIXE false
#define SENSROTATION 1
#define RAYONOBSCURITE 10
#define COULEUROBSCURITE QColor(0, 0, 0, 255)
#define ANGLEROTATIONAUHASARD false
#define INTERVALLEROTATIONAUHASARD false
#define SENSROTATIONAUHASARD false
#define POURCENTAGEDISTORSIONVERTICALE 100
#define POURCENTAGEDISTORSIONHORIZONTALE 100
#define POURCENTAGEDISTORSIONVERTICALEAUHASARD false
#define POURCENTAGEDISTORSIONHORIZONTALEAUHASARD false
#define INTERVALLEDISTORSIONVERTICALE 50
#define INTERVALLEDISTORSIONHORIZONTALE 25
#define INTERVALLEDISTORSIONVERTICALEAUHASARD false
#define INTERVALLEDISTORSIONHORIZONTALEAUHASARD false
#define DISTORSIONSYNCHRONISEE false
#define DISTORSIONSYNCHRONISEEAUHASARD false
#define INTERVALLEDISTORSIONVERTICALEMAX 1*60*1000
#define INTERVALLEDISTORSIONVERTICALEMIN 10
#define INTERVALLEDISTORSIONHORIZONTALEMAX 1*60*1000
#define INTERVALLEDISTORSIONHORIZONTALEMIN 10
#define DISTORSIONVERTICALEFIXE false
#define DISTORSIONHORIZONTALEFIXE false
#define POURCENTAGECISAILLEMENTVERTICAL 100
#define POURCENTAGECISAILLEMENTHORIZONTAL 100
#define POURCENTAGECISAILLEMENTVERTICALAUHASARD false
#define POURCENTAGECISAILLEMENTHORIZONTALAUHASARD false
#define INTERVALLECISAILLEMENTVERTICAL 50
#define INTERVALLECISAILLEMENTHORIZONTAL 25
#define INTERVALLECISAILLEMENTVERTICALAUHASARD false
#define INTERVALLECISAILLEMENTHORIZONTALAUHASARD false
#define CISAILLEMENTSYNCHRONISE false
#define CISAILLEMENTSYNCHRONISEAUHASARD false
#define INTERVALLECISAILLEMENTVERTICALMAX 1*60*1000
#define INTERVALLECISAILLEMENTVERTICALMIN 10
#define INTERVALLECISAILLEMENTHORIZONTALMAX 1*60*1000
#define INTERVALLECISAILLEMENTHORIZONTALMIN 10
#define CISAILLEMENTVERTICALFIXE false
#define CISAILLEMENTHORIZONTALFIXE false

//Constantes pour le labyrinthe 3D

#define PASANGLEJEU 5.0
#define PASDISTANCEJEU 1.0
#define PASANGLERESOLUTION 2.5
#define PASDISTANCERESOLUTION 0.4
#define HAUTEURFACILE 51
#define HAUTEURMOYEN 71
#define HAUTEURDIFFICILE 91
#define HAUTEURCASE 10

#endif // CONSTANTS_H
